[package]
name = "validators"
version = "0.18.5"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/validators"
homepage = "https://magiclen.org/validators"
keywords = ["validator", "validation", "user", "rocket", "serde"]
categories = ["value-formatting"]
description= "A library for validating user input."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/validators", branch = "master" }
appveyor = { repository = "magiclen/validators", branch = "master", service = "github" }

[dependencies]
regex = "1.0"
number-as = "1.0"
lazy_static = "1.1"
rocket = { version = "0.3.16", optional = true }
rocket_codegen = { version = "0.3.16", optional = true }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
phonenumber = { version = "0.2.1+8.9.0", optional = true }

[features]
nightly = []
rocketly = ["nightly", "rocket"]
rocketly-test = ["rocketly", "rocket_codegen"]
serdely = ["serde", "serde_json"]
serdely-test = ["serdely"]
phone_number = ["phonenumber"]
phone_ac = ["phone_number"]
phone_ad = ["phone_number"]
phone_ae = ["phone_number"]
phone_af = ["phone_number"]
phone_ag = ["phone_number"]
phone_ai = ["phone_number"]
phone_al = ["phone_number"]
phone_am = ["phone_number"]
phone_ao = ["phone_number"]
phone_ar = ["phone_number"]
phone_as = ["phone_number"]
phone_at = ["phone_number"]
phone_au = ["phone_number"]
phone_aw = ["phone_number"]
phone_ax = ["phone_number"]
phone_az = ["phone_number"]
phone_ba = ["phone_number"]
phone_bb = ["phone_number"]
phone_bd = ["phone_number"]
phone_be = ["phone_number"]
phone_bf = ["phone_number"]
phone_bg = ["phone_number"]
phone_bh = ["phone_number"]
phone_bi = ["phone_number"]
phone_bj = ["phone_number"]
phone_bl = ["phone_number"]
phone_bm = ["phone_number"]
phone_bn = ["phone_number"]
phone_bo = ["phone_number"]
phone_bq = ["phone_number"]
phone_br = ["phone_number"]
phone_bs = ["phone_number"]
phone_bt = ["phone_number"]
phone_bw = ["phone_number"]
phone_by = ["phone_number"]
phone_bz = ["phone_number"]
phone_ca = ["phone_number"]
phone_cc = ["phone_number"]
phone_cd = ["phone_number"]
phone_cf = ["phone_number"]
phone_cg = ["phone_number"]
phone_ch = ["phone_number"]
phone_ci = ["phone_number"]
phone_ck = ["phone_number"]
phone_cl = ["phone_number"]
phone_cm = ["phone_number"]
phone_cn = ["phone_number"]
phone_co = ["phone_number"]
phone_cr = ["phone_number"]
phone_cu = ["phone_number"]
phone_cv = ["phone_number"]
phone_cw = ["phone_number"]
phone_cx = ["phone_number"]
phone_cy = ["phone_number"]
phone_cz = ["phone_number"]
phone_de = ["phone_number"]
phone_dj = ["phone_number"]
phone_dk = ["phone_number"]
phone_dm = ["phone_number"]
phone_do = ["phone_number"]
phone_dz = ["phone_number"]
phone_ec = ["phone_number"]
phone_ee = ["phone_number"]
phone_eg = ["phone_number"]
phone_eh = ["phone_number"]
phone_er = ["phone_number"]
phone_es = ["phone_number"]
phone_et = ["phone_number"]
phone_fi = ["phone_number"]
phone_fj = ["phone_number"]
phone_fk = ["phone_number"]
phone_fm = ["phone_number"]
phone_fo = ["phone_number"]
phone_fr = ["phone_number"]
phone_ga = ["phone_number"]
phone_gb = ["phone_number"]
phone_gd = ["phone_number"]
phone_ge = ["phone_number"]
phone_gf = ["phone_number"]
phone_gg = ["phone_number"]
phone_gh = ["phone_number"]
phone_gi = ["phone_number"]
phone_gl = ["phone_number"]
phone_gm = ["phone_number"]
phone_gn = ["phone_number"]
phone_gp = ["phone_number"]
phone_gq = ["phone_number"]
phone_gr = ["phone_number"]
phone_gt = ["phone_number"]
phone_gu = ["phone_number"]
phone_gw = ["phone_number"]
phone_gy = ["phone_number"]
phone_hk = ["phone_number"]
phone_hn = ["phone_number"]
phone_hr = ["phone_number"]
phone_ht = ["phone_number"]
phone_hu = ["phone_number"]
phone_id = ["phone_number"]
phone_ie = ["phone_number"]
phone_il = ["phone_number"]
phone_im = ["phone_number"]
phone_in = ["phone_number"]
phone_io = ["phone_number"]
phone_iq = ["phone_number"]
phone_ir = ["phone_number"]
phone_is = ["phone_number"]
phone_it = ["phone_number"]
phone_je = ["phone_number"]
phone_jm = ["phone_number"]
phone_jo = ["phone_number"]
phone_jp = ["phone_number"]
phone_ke = ["phone_number"]
phone_kg = ["phone_number"]
phone_kh = ["phone_number"]
phone_ki = ["phone_number"]
phone_km = ["phone_number"]
phone_kn = ["phone_number"]
phone_kp = ["phone_number"]
phone_kr = ["phone_number"]
phone_kw = ["phone_number"]
phone_ky = ["phone_number"]
phone_kz = ["phone_number"]
phone_la = ["phone_number"]
phone_lb = ["phone_number"]
phone_lc = ["phone_number"]
phone_li = ["phone_number"]
phone_lk = ["phone_number"]
phone_lr = ["phone_number"]
phone_ls = ["phone_number"]
phone_lt = ["phone_number"]
phone_lu = ["phone_number"]
phone_lv = ["phone_number"]
phone_ly = ["phone_number"]
phone_ma = ["phone_number"]
phone_mc = ["phone_number"]
phone_md = ["phone_number"]
phone_me = ["phone_number"]
phone_mf = ["phone_number"]
phone_mg = ["phone_number"]
phone_mh = ["phone_number"]
phone_mk = ["phone_number"]
phone_ml = ["phone_number"]
phone_mm = ["phone_number"]
phone_mn = ["phone_number"]
phone_mo = ["phone_number"]
phone_mp = ["phone_number"]
phone_mq = ["phone_number"]
phone_mr = ["phone_number"]
phone_ms = ["phone_number"]
phone_mt = ["phone_number"]
phone_mu = ["phone_number"]
phone_mv = ["phone_number"]
phone_mw = ["phone_number"]
phone_mx = ["phone_number"]
phone_my = ["phone_number"]
phone_mz = ["phone_number"]
phone_na = ["phone_number"]
phone_nc = ["phone_number"]
phone_ne = ["phone_number"]
phone_nf = ["phone_number"]
phone_ng = ["phone_number"]
phone_ni = ["phone_number"]
phone_nl = ["phone_number"]
phone_no = ["phone_number"]
phone_np = ["phone_number"]
phone_nr = ["phone_number"]
phone_nu = ["phone_number"]
phone_nz = ["phone_number"]
phone_om = ["phone_number"]
phone_pa = ["phone_number"]
phone_pe = ["phone_number"]
phone_pf = ["phone_number"]
phone_pg = ["phone_number"]
phone_ph = ["phone_number"]
phone_pk = ["phone_number"]
phone_pl = ["phone_number"]
phone_pm = ["phone_number"]
phone_pr = ["phone_number"]
phone_ps = ["phone_number"]
phone_pt = ["phone_number"]
phone_pw = ["phone_number"]
phone_py = ["phone_number"]
phone_qa = ["phone_number"]
phone_re = ["phone_number"]
phone_ro = ["phone_number"]
phone_rs = ["phone_number"]
phone_ru = ["phone_number"]
phone_rw = ["phone_number"]
phone_sa = ["phone_number"]
phone_sb = ["phone_number"]
phone_sc = ["phone_number"]
phone_sd = ["phone_number"]
phone_se = ["phone_number"]
phone_sg = ["phone_number"]
phone_sh = ["phone_number"]
phone_si = ["phone_number"]
phone_sj = ["phone_number"]
phone_sk = ["phone_number"]
phone_sl = ["phone_number"]
phone_sm = ["phone_number"]
phone_sn = ["phone_number"]
phone_so = ["phone_number"]
phone_sr = ["phone_number"]
phone_ss = ["phone_number"]
phone_st = ["phone_number"]
phone_sv = ["phone_number"]
phone_sx = ["phone_number"]
phone_sy = ["phone_number"]
phone_sz = ["phone_number"]
phone_ta = ["phone_number"]
phone_tc = ["phone_number"]
phone_td = ["phone_number"]
phone_tg = ["phone_number"]
phone_th = ["phone_number"]
phone_tj = ["phone_number"]
phone_tk = ["phone_number"]
phone_tl = ["phone_number"]
phone_tm = ["phone_number"]
phone_tn = ["phone_number"]
phone_to = ["phone_number"]
phone_tr = ["phone_number"]
phone_tt = ["phone_number"]
phone_tv = ["phone_number"]
phone_tw = ["phone_number"]
phone_tz = ["phone_number"]
phone_ua = ["phone_number"]
phone_ug = ["phone_number"]
phone_us = ["phone_number"]
phone_uy = ["phone_number"]
phone_uz = ["phone_number"]
phone_va = ["phone_number"]
phone_vc = ["phone_number"]
phone_ve = ["phone_number"]
phone_vg = ["phone_number"]
phone_vi = ["phone_number"]
phone_vn = ["phone_number"]
phone_vu = ["phone_number"]
phone_wf = ["phone_number"]
phone_ws = ["phone_number"]
phone_ye = ["phone_number"]
phone_yt = ["phone_number"]
phone_za = ["phone_number"]
phone_zm = ["phone_number"]
phone_zw = ["phone_number"]
phone = ["phone_ac", "phone_ad", "phone_ae", "phone_af", "phone_ag", "phone_ai", "phone_al", "phone_am", "phone_ao", "phone_ar", "phone_as", "phone_at", "phone_au", "phone_aw", "phone_ax", "phone_az", "phone_ba", "phone_bb", "phone_bd", "phone_be", "phone_bf", "phone_bg", "phone_bh", "phone_bi", "phone_bj", "phone_bl", "phone_bm", "phone_bn", "phone_bo", "phone_bq", "phone_br", "phone_bs", "phone_bt", "phone_bw", "phone_by", "phone_bz", "phone_ca", "phone_cc", "phone_cd", "phone_cf", "phone_cg", "phone_ch", "phone_ci", "phone_ck", "phone_cl", "phone_cm", "phone_cn", "phone_co", "phone_cr", "phone_cu", "phone_cv", "phone_cw", "phone_cx", "phone_cy", "phone_cz", "phone_de", "phone_dj", "phone_dk", "phone_dm", "phone_do", "phone_dz", "phone_ec", "phone_ee", "phone_eg", "phone_eh", "phone_er", "phone_es", "phone_et", "phone_fi", "phone_fj", "phone_fk", "phone_fm", "phone_fo", "phone_fr", "phone_ga", "phone_gb", "phone_gd", "phone_ge", "phone_gf", "phone_gg", "phone_gh", "phone_gi", "phone_gl", "phone_gm", "phone_gn", "phone_gp", "phone_gq", "phone_gr", "phone_gt", "phone_gu", "phone_gw", "phone_gy", "phone_hk", "phone_hn", "phone_hr", "phone_ht", "phone_hu", "phone_id", "phone_ie", "phone_il", "phone_im", "phone_in", "phone_io", "phone_iq", "phone_ir", "phone_is", "phone_it", "phone_je", "phone_jm", "phone_jo", "phone_jp", "phone_ke", "phone_kg", "phone_kh", "phone_ki", "phone_km", "phone_kn", "phone_kp", "phone_kr", "phone_kw", "phone_ky", "phone_kz", "phone_la", "phone_lb", "phone_lc", "phone_li", "phone_lk", "phone_lr", "phone_ls", "phone_lt", "phone_lu", "phone_lv", "phone_ly", "phone_ma", "phone_mc", "phone_md", "phone_me", "phone_mf", "phone_mg", "phone_mh", "phone_mk", "phone_ml", "phone_mm", "phone_mn", "phone_mo", "phone_mp", "phone_mq", "phone_mr", "phone_ms", "phone_mt", "phone_mu", "phone_mv", "phone_mw", "phone_mx", "phone_my", "phone_mz", "phone_na", "phone_nc", "phone_ne", "phone_nf", "phone_ng", "phone_ni", "phone_nl", "phone_no", "phone_np", "phone_nr", "phone_nu", "phone_nz", "phone_om", "phone_pa", "phone_pe", "phone_pf", "phone_pg", "phone_ph", "phone_pk", "phone_pl", "phone_pm", "phone_pr", "phone_ps", "phone_pt", "phone_pw", "phone_py", "phone_qa", "phone_re", "phone_ro", "phone_rs", "phone_ru", "phone_rw", "phone_sa", "phone_sb", "phone_sc", "phone_sd", "phone_se", "phone_sg", "phone_sh", "phone_si", "phone_sj", "phone_sk", "phone_sl", "phone_sm", "phone_sn", "phone_so", "phone_sr", "phone_ss", "phone_st", "phone_sv", "phone_sx", "phone_sy", "phone_sz", "phone_ta", "phone_tc", "phone_td", "phone_tg", "phone_th", "phone_tj", "phone_tk", "phone_tl", "phone_tm", "phone_tn", "phone_to", "phone_tr", "phone_tt", "phone_tv", "phone_tw", "phone_tz", "phone_ua", "phone_ug", "phone_us", "phone_uy", "phone_uz", "phone_va", "phone_vc", "phone_ve", "phone_vg", "phone_vi", "phone_vn", "phone_vu", "phone_wf", "phone_ws", "phone_ye", "phone_yt", "phone_za", "phone_zm", "phone_zw"]

[package.metadata.docs.rs]
all-features = true